name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write  # Changed from 'read' to 'write' to allow branch creation
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create build directory structure
        run: |
          mkdir -p build
          mkdir -p build/static

      - name: Generate OpenAPI JSON
        run: |
          # Make sure the build directory exists
          mkdir -p build
          # Generate the OpenAPI schema from your FastAPI app
          python scripts/generate_openapi.py

      - name: Copy HTML files to build directory
        run: |
          cp app/templates/html/index.html build/index.html
          cp app/templates/html/swagger_doc.html build/swagger_doc.html

      - name: Copy static files
        run: |
          cp -r app/templates/static/* build/static/
          ls -la build/static

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build
          branch: gh-pages
